#!/usr/bin/env python3
"""Generate a real torus-knot mesh and its animated README preview."""

from __future__ import annotations

import math
from pathlib import Path
from typing import TypeAlias

ROOT = Path(__file__).resolve().parents[1]
ASSETS = ROOT / "assets"
MODELS = ASSETS / "models"

Vec3: TypeAlias = tuple[float, float, float]
Face: TypeAlias = tuple[int, int, int]

RINGS = 96
SIDES = 18
MAJOR_RADIUS = 2.25
MINOR_RADIUS = 0.78
TUBE_RADIUS = 0.22


def add(a: Vec3, b: Vec3) -> Vec3:
    """Add two vectors."""
    return (a[0] + b[0], a[1] + b[1], a[2] + b[2])


def subtract(a: Vec3, b: Vec3) -> Vec3:
    """Subtract two vectors."""
    return (a[0] - b[0], a[1] - b[1], a[2] - b[2])


def scale(vector: Vec3, amount: float) -> Vec3:
    """Scale a vector."""
    return tuple(component * amount for component in vector)  # type: ignore[return-value]


def dot(a: Vec3, b: Vec3) -> float:
    """Return the vector dot product."""
    return a[0] * b[0] + a[1] * b[1] + a[2] * b[2]


def cross(a: Vec3, b: Vec3) -> Vec3:
    """Return the vector cross product."""
    return (
        a[1] * b[2] - a[2] * b[1],
        a[2] * b[0] - a[0] * b[2],
        a[0] * b[1] - a[1] * b[0],
    )


def normalize(vector: Vec3) -> Vec3:
    """Normalize a non-zero vector."""
    length = math.sqrt(dot(vector, vector))
    if length < 1e-12:
        raise ValueError("Cannot normalize a zero-length vector")
    return scale(vector, 1.0 / length)


def centerline(t: float) -> Vec3:
    """Return a point on a (2, 3) torus knot."""
    radial = MAJOR_RADIUS + MINOR_RADIUS * math.cos(3 * t)
    return (
        radial * math.cos(2 * t),
        radial * math.sin(2 * t),
        MINOR_RADIUS * math.sin(3 * t),
    )


def tangent(t: float) -> Vec3:
    """Approximate the knot tangent with a centred finite difference."""
    delta = 1e-4
    return normalize(subtract(centerline(t + delta), centerline(t - delta)))


def build_mesh() -> tuple[list[Vec3], list[Face]]:
    """Create the closed tube mesh around the knot centerline."""
    vertices: list[Vec3] = []
    frames: list[tuple[Vec3, Vec3]] = []
    previous_normal: Vec3 | None = None

    for ring in range(RINGS):
        t = math.tau * ring / RINGS
        direction = tangent(t)
        if previous_normal is None:
            reference = (0.0, 0.0, 1.0)
            normal = normalize(cross(direction, reference))
        else:
            transported = subtract(
                previous_normal, scale(direction, dot(previous_normal, direction))
            )
            normal = normalize(transported)
        binormal = normalize(cross(direction, normal))
        frames.append((normal, binormal))
        previous_normal = normal

    for ring, (normal, binormal) in enumerate(frames):
        t = math.tau * ring / RINGS
        center = centerline(t)
        for side in range(SIDES):
            angle = math.tau * side / SIDES
            offset = add(
                scale(normal, TUBE_RADIUS * math.cos(angle)),
                scale(binormal, TUBE_RADIUS * math.sin(angle)),
            )
            vertices.append(add(center, offset))

    faces: list[Face] = []
    for ring in range(RINGS):
        next_ring = (ring + 1) % RINGS
        for side in range(SIDES):
            next_side = (side + 1) % SIDES
            a = ring * SIDES + side
            b = next_ring * SIDES + side
            c = next_ring * SIDES + next_side
            d = ring * SIDES + next_side
            faces.extend([(a, b, c), (a, c, d)])
    return vertices, faces


def face_normal(vertices: list[Vec3], face: Face) -> Vec3:
    """Calculate one triangle normal."""
    a, b, c = (vertices[index] for index in face)
    return normalize(cross(subtract(b, a), subtract(c, a)))


def write_stl(vertices: list[Vec3], faces: list[Face]) -> None:
    """Write an ASCII STL that GitHub and modelling tools can inspect."""
    lines = ["solid curiosity_knot"]
    for face in faces:
        normal = face_normal(vertices, face)
        lines.append(f"  facet normal {normal[0]:.7f} {normal[1]:.7f} {normal[2]:.7f}")
        lines.append("    outer loop")
        for index in face:
            vertex = vertices[index]
            lines.append(f"      vertex {vertex[0]:.7f} {vertex[1]:.7f} {vertex[2]:.7f}")
        lines.extend(["    endloop", "  endfacet"])
    lines.append("endsolid curiosity_knot")
    (MODELS / "curiosity-knot.stl").write_text("\n".join(lines) + "\n", encoding="ascii")


def write_obj(vertices: list[Vec3], faces: list[Face]) -> None:
    """Write the same mesh as a portable Wavefront OBJ."""
    lines = ["# Curiosity Knot - generated by scripts/build_3d_mesh.py", "o CuriosityKnot"]
    lines.extend(f"v {x:.7f} {y:.7f} {z:.7f}" for x, y, z in vertices)
    lines.extend(f"f {a + 1} {b + 1} {c + 1}" for a, b, c in faces)
    (MODELS / "curiosity-knot.obj").write_text("\n".join(lines) + "\n", encoding="ascii")


def project(vertex: Vec3, yaw: float, pitch: float) -> tuple[float, float]:
    """Project a rotated 3D vertex into the wireframe viewport."""
    x, y, z = vertex
    x1 = math.cos(yaw) * x - math.sin(yaw) * y
    y1 = math.sin(yaw) * x + math.cos(yaw) * y
    y2 = math.cos(pitch) * y1 - math.sin(pitch) * z
    z2 = math.sin(pitch) * y1 + math.cos(pitch) * z
    perspective = 1.0 / (1.0 + 0.055 * z2)
    return (600 + x1 * 137 * perspective, 272 - y2 * 137 * perspective)


def path(points: list[tuple[float, float]], close: bool = False) -> str:
    """Convert projected points to a compact SVG path."""
    commands = [f"M{points[0][0]:.1f} {points[0][1]:.1f}"]
    commands.extend(f"L{x:.1f} {y:.1f}" for x, y in points[1:])
    if close:
        commands.append("Z")
    return "".join(commands)


def wireframe_group(vertices: list[Vec3], yaw: float, phase: int) -> str:
    """Build one projected mesh phase used by the cross-fade animation."""
    projected = [project(vertex, yaw, -0.48) for vertex in vertices]
    paths: list[str] = []
    for ring in range(0, RINGS, 3):
        points = [projected[ring * SIDES + side] for side in range(SIDES)]
        paths.append(f'<path d="{path(points, close=True)}"/>')
    for side in range(0, SIDES, 2):
        points = [projected[ring * SIDES + side] for ring in range(RINGS)]
        paths.append(f'<path d="{path(points, close=True)}"/>')
    return f'<g class="mesh phase{phase}">{"".join(paths)}</g>'


def write_preview(vertices: list[Vec3]) -> None:
    """Write an animated, GitHub-compatible SVG preview of the 3D model."""
    phases = [wireframe_group(vertices, yaw, index) for index, yaw in enumerate((0.2, 0.85, 1.5))]
    document = f"""<svg xmlns="http://www.w3.org/2000/svg" width="1200" height="544" viewBox="0 0 1200 544" role="img" aria-labelledby="title desc">
<title id="title">Curiosity Knot parametric mesh</title>
<desc id="desc">An animated wireframe preview of a downloadable torus-knot STL and OBJ model.</desc>
<defs>
  <linearGradient id="meshSignal" x1="0" y1="0" x2="1" y2="1">
    <stop offset="0" stop-color="#63D9D1"/><stop offset=".5" stop-color="#B89DFF"/><stop offset="1" stop-color="#FF9B7A"/>
  </linearGradient>
  <radialGradient id="meshBg"><stop stop-color="#111A35"/><stop offset="1" stop-color="#03050C"/></radialGradient>
  <pattern id="meshGrid" width="34" height="34" patternUnits="userSpaceOnUse"><path d="M34 0H0V34" fill="none" stroke="#EAF4FF" stroke-opacity=".045"/></pattern>
  <filter id="meshGlow" x="-100%" y="-100%" width="300%" height="300%"><feGaussianBlur stdDeviation="5" result="b"/><feMerge><feMergeNode in="b"/><feMergeNode in="SourceGraphic"/></feMerge></filter>
  <style><![CDATA[
    .mesh{{fill:none;stroke:url(#meshSignal);stroke-width:1.2;stroke-opacity:.56;stroke-linejoin:round}}
    .phase0{{animation:p0 12s ease-in-out infinite}}.phase1{{animation:p1 12s ease-in-out infinite}}.phase2{{animation:p2 12s ease-in-out infinite}}
    .orbit{{transform-box:fill-box;transform-origin:center;animation:turn 18s linear infinite}}
    .dash{{stroke-dasharray:7 14;animation:flow 14s linear infinite}}
    .pulse{{transform-box:fill-box;transform-origin:center;animation:pulse 3s ease-in-out infinite}}
    @keyframes p0{{0%,24%,100%{{opacity:1}}36%,88%{{opacity:0}}}}@keyframes p1{{0%,22%,78%,100%{{opacity:0}}36%,57%{{opacity:1}}}}@keyframes p2{{0%,55%,100%{{opacity:0}}68%,88%{{opacity:1}}}}
    @keyframes turn{{to{{transform:rotate(360deg)}}}}@keyframes flow{{to{{stroke-dashoffset:-420}}}}@keyframes pulse{{0%,100%{{opacity:.35;transform:scale(.82)}}50%{{opacity:1;transform:scale(1.14)}}}}
    @media(prefers-reduced-motion:reduce){{*{{animation:none!important}}.phase1,.phase2{{display:none}}}}
  ]]></style>
</defs>
<rect width="1200" height="544" rx="30" fill="url(#meshBg)"/><rect width="1200" height="544" rx="30" fill="url(#meshGrid)"/>
<path d="M38 410C228 240 364 486 568 300S876 174 1160 332" fill="none" stroke="url(#meshSignal)" stroke-width="2" class="dash" opacity=".48"/>
<g class="orbit" opacity=".5"><ellipse cx="600" cy="272" rx="484" ry="188" fill="none" stroke="url(#meshSignal)" stroke-width="1.5" stroke-dasharray="4 18"/></g>
{"".join(phases)}
<g filter="url(#meshGlow)"><circle cx="188" cy="222" r="6" fill="#63D9D1" class="pulse"/><circle cx="1018" cy="316" r="6" fill="#FF9B7A" class="pulse"/><circle cx="600" cy="272" r="7" fill="#FFF9EF" class="pulse"/></g>
<path d="M30 78V30H78M1122 30h48v48M30 466v48h48M1122 514h48v-48" fill="none" stroke="#F3EBDD" stroke-opacity=".3" stroke-width="2"/>
<rect x="1" y="1" width="1198" height="542" rx="29" fill="none" stroke="#E9F3FF" stroke-opacity=".16"/>
</svg>"""
    (ASSETS / "curiosity-knot-wireframe.svg").write_text(document, encoding="utf-8")


def main() -> None:
    """Generate the mesh formats and animated wireframe preview."""
    MODELS.mkdir(parents=True, exist_ok=True)
    vertices, faces = build_mesh()
    write_stl(vertices, faces)
    write_obj(vertices, faces)
    write_preview(vertices)
    print(f"Generated {len(vertices)} vertices and {len(faces)} faces in STL, OBJ, and SVG formats")


if __name__ == "__main__":
    main()
